---
title: "datamanipulation"
author: "Rachel Lee"
date: "3/10/2020"
output: html_document
---
```{r}
library(tidyverse)

options(tibble.print_min = 3)

litters_data = read_csv("/Users/rachellee/Desktop/ds_data/FAS_litters.csv", 
    col_types = "ccddiiii")

####what is "ccddiiii"???????


litters_data = janitor::clean_names(litters_data)

pups_data = read_csv("/Users/rachellee/Desktop/ds_data/FAS_pups.csv",
    col_types = "ciiiii")
pups_data = janitor::clean_names(pups_data)

#selecting specific columns from "litters_data"
select(litters_data, group, litter_number, gd0_weight, pups_born_alive) 
####why isn't it modifying the actual dataset?



#select a range of columns to keep
select(litters_data, group:gd_of_birth)

#remove columns using 'select'
select(litters_data, -pups_survive)

#rename variables using 'select' -> this renames & selects at the same time
select(litters_data, GROUP = group, LittER_NUMber = litter_number)

#'rename' -->rename the variable that you care about and keep the rest
rename(litters_data, GROUP = group, LiTTER_Number = litter_number)

# ?select_helpers --> functions relevant to 'select'. One of them is 'everything()'
select(litters_data, litter_number, group, everything())
##switched the order of litter_number and group, keep the rest as the same

#drop all missing values in 'litters_data'
drop_na(litters_data)


#filter to include only pups with sex 1
filter(pups_data, sex == 1)


#filter to include only pus with PD walk less than 11 and sex 2
filter(pups_data, sex==2, pd_walk<11 )

#######################################
#mutate : modify or create new columns

mutate(litters_data,
       wt_gain = gd18_weight - gd0_weight, #creating a new variable called 'wt_gain'
       group = str_to_lower(group) #modifying character variable 'group' to lower case
       )

#A few things in this example are worth noting:
  ##Your new variables can be functions of old variables
  ##New variables appear at the end of the dataset in the order that     they are created
  ##You can overwrite old variables
  ##You can create a new variable and immediately refer to (or          change) it



mutate(pups_data, 
       pivot_minus7 = pd_pivot - 7)

mutate(pups_data, 
       pd_sum =  pd_ears + pd_eyes + pd_pivot + pd_walk)

head(arrange(litters_data, group, pups_born_alive), 10)


```

```{r}
litters_data = 
  read_csv("/Users/rachellee/Desktop/ds_data/FAS_litters.csv", col_types = "ccddiiii") %>%
  janitor::clean_names() %>%
  select(-pups_survive) %>%
  mutate(
    wt_gain = gd18_weight - gd0_weight,
    group = str_to_lower(group)) %>%
  drop_na(wt_gain)

litters_data
```


```{r}
pups_data = 
  read_csv("/Users/rachellee/Desktop/ds_data/FAS_pups.csv",
    col_types = "ciiiii") %>%
  janitor::clean_names() %>%
  filter(sex == 1) %>%
  select(-pd_ears) %>%
  mutate(pd_pivot_gt7 = pd_pivot > 7)
  
pups_data

```

